### ISSUE TITLE
Broken on Ubuntu 20.04

### ISSUE THREAD

**Issue by sergeykad** [arelange/gnome-shell-extension-hibernate-status#49]
No Hibernate menu option and there is the following error

The settings of extension hibernate-status@dromi had an error:
```
Error: Expected type object for Argument 'widget' but got type 'undefined'
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:208:25
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by p91paul** [comment]
The extension was updated for gs 3.36 and works on Debian and Arch at least, so hibernate button should show up.
Did you try following the FAQ section on the homepage https://github.com/arelange/gnome-shell-extension-hibernate-status? Ubuntu in the past needed some tweaking to make hibernation work & make it available to the extension.

I can instead reproduce your error when loading the preferences page, but it's unrelated. It's even possible we never actually implemented the page because we just store a couple "do not show this again" options, so it's not very useful.

**Comment by abhidesh128** [comment]
I have the same error, but hibernate and hybrid sleep works for me. Just, the settings are not accessible. Is the preferences page really implemented ? or is it being shown wrongly due to another reason ?

**Comment by DanMan** [comment]
Same issue on Fedora 32 with Gnome Shell 3.36.2.

**Comment by p91paul** [comment]
I confirm we never implemented the preferences page because it's not really useful.

**Comment by dannyk81** [comment]
Running this extension on Pop!_OS 20.04 (based on Ubuntu 20.04) and works just fine:
![image](https://user-images.githubusercontent.com/24274156/82274573-7b19ab00-994e-11ea-893a-5f222ba171ba.png)

It does show an ERROR in Installed Extensions page, but it looks like it's due to the unimplemented preferences page.

I did have to follow the instructions mentioned in the README to get things working properly.

**Comment by elpraga** [comment]
I can confirm, it does work on Ubuntu 20.04 applying the instructions mentioned in the README file.

I can also confirm though the error when bringing up the configuration dialogue.

```
Error: Expected type object for Argument 'widget' but got type 'undefined'

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:208:25
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

**Comment by DanMan** [comment]
Well, on Fedora 32 it now shows up, but clicking Hibernate doesn't do anything anymore.
